name: Feature Request
description: Suggest a new feature or enhancement for the website
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - nayandas69

body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for suggesting a feature!
        Please provide as much detail as possible about your idea.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Must have)
        - High (Very important)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Dashboard/Control Panel
        - Documentation/Guides
        - UI/UX Improvement
        - Navigation/Layout
        - New Page/Section
        - Performance/Speed
        - SEO/Accessibility
        - Integration (API/Bot)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why do you need it?
      placeholder: Explain the problem this solves...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: Describe how it should work...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe alternatives you've considered...

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        1. When a user wants to...
        2. When an admin needs to...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If you have any mockups, wireframes, or examples from other sites, share them here
      placeholder: Add images or links to examples...

  - type: dropdown
    id: implementation
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature is to implement?
      options:
        - Simple (Small UI change)
        - Medium (New component/page)
        - Complex (Major feature/integration)
        - Not sure
    validations:
      required: false

  - type: checkboxes
    id: contribute
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I'd like to help implement this feature
          required: false
        - label: I can provide design mockups
          required: false
        - label: I can help with testing
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the feature request here
      placeholder: Any additional information...
